most content on page, added formatting
RND-Tech-and-Design/erindtherapy pull request #11
Opened 2024-01-17 03:08 UTC by PhoenixMP

2024-01-20 19:17 UTC, RyanDrx requested changes

2024-01-20 19:17 UTC, RyanDrx commented on pages/services/marathonCouplesTherapy.vue
> +                    "There is an undisclosed, current affair that you are not willing to disclose (such secrets predict marital therapy failure)",
Can this section use red X's instead of dots?

2024-01-20 19:17 UTC, RyanDrx commented on pages/services/marathonCouplesTherapy.vue
> +                        class="mt-10 md:hidden " />
I appreciate the consideration for mobile responsiveness. However, since both components are currently being rendered and merely hidden with CSS, it might be more efficient to either merge these components or enclose them within a wrapper that evaluates the screen width to determine if the device is mobile. Utilizing v-if="mobile" or v-if="!mobile" can then selectively render the appropriate component, preventing unnecessary execution.

I do something similar in the carousel component by watching the screen to determine when a button should be visible.

2024-02-25 23:06 UTC, PhoenixMP commented on pages/services/marathonCouplesTherapy.vue
> +                    "There is an undisclosed, current affair that you are not willing to disclose (such secrets predict marital therapy failure)",
Done!
![image](https://github.com/RND-Tech-and-Design/erindtherapy/assets/112582143/7fce3068-f476-48d6-a738-47150e99f23b)

2024-02-25 23:39 UTC, PhoenixMP commented on pages/services/marathonCouplesTherapy.vue
> +                        class="mt-10 md:hidden " />
Done! 
![image](https://github.com/RND-Tech-and-Design/erindtherapy/assets/112582143/ee2793be-7d62-44e9-a475-819252b03fed)
![image](https://github.com/RND-Tech-and-Design/erindtherapy/assets/112582143/385c2dd9-635e-4bff-af3f-e02612d4bfb9)

2024-03-06 06:14 UTC, merged