About me page
RND-Tech-and-Design/erindtherapy pull request #6
Opened 2024-01-05 23:17 UTC by PhoenixMP

First-draft of the "about" page, copying the format of the original website page. 

![image](https://github.com/RND-Tech-and-Design/erindtherapy/assets/112582143/fe6fb162-5319-4a2a-8070-0d1eb7f157f7)
![image](https://github.com/RND-Tech-and-Design/erindtherapy/assets/112582143/76aab763-63ac-4667-96ce-3973ab75e901)

2024-01-06 01:33 UTC, RyanDrx requested changes
Some minor nits or otherwise some advice. 

Everything looks excellent, and you did a great job emulating the current page.  I like how you destructured the components into layout and data. That is really helpful for making changes later or for quickly spinning up a page for SEO targeting. 

I also viewed with mobile and it looks great. The only issue is Erin's portrait is HUGE on mobile. :)

2024-01-06 01:33 UTC, RyanDrx commented on package.json
> +        "@fortawesome/fontawesome-free": "^6.5.1",
Probably do not need this dependency, as the nuxt-icon and hero-icons takes care of it.  Also pretty sure fontawesome is already installed and the icons can be used. 

We can use any icon from here https://icones.js.org/ which includes every icon library


example usage


```
  <icon name="bxs:quote-right" size="1em" class="flex-none min-w-8"></icon>
```

2024-01-08 20:26 UTC, PhoenixMP commented on components/AboutMePage/Qualification.vue
> +    <div class="mt-5 mb-5 lg:text-4xl lg:mb-5 text-2xl font-medium">
I like it better center:
![image](https://github.com/RND-Tech-and-Design/erindtherapy/assets/112582143/6a6b0f7e-511c-4c1d-a6ee-e92e72dfe7d3)

2024-01-08 20:34 UTC, PhoenixMP commented on pages/about.vue
> +        text: "I am eager to help driven, smart, talented individuals embrace their strengths and start a career and life they aspire to.",
I saw you doing an array of strings on a different component and that's where I got the idea, but I noticed that some sections on the about page had altered text in the paragraphs. Those text objects have an added key of "styleType" (fig-1). Right now in my AboutMePage-Section component, an extra class for styling is applied to the paragraph text if that styleType key exists in the object (fig-2). 

I could have added styleType to all  of the objects for clarity and set those values to "" if there's no extra styling needed, and change the component to search for a styleType value >0?
Or I could have a separate styleStype array and define if there are additional styleTypes in the corresponding index.

Let me know if there's a better way you see that I am not thinking of!

![image](https://github.com/RND-Tech-and-Design/erindtherapy/assets/112582143/a6acb365-8ba4-4f16-bb60-73887d33622f)
![image](https://github.com/RND-Tech-and-Design/erindtherapy/assets/112582143/cc75df0c-60d3-4c38-8686-a1842d75798f)

2024-01-08 21:47 UTC, PhoenixMP commented on components/AboutMePage/Intro.vue
> +const props = defineProps({ data: Object });
I've declared more specific types for each of the components in the AboutMePage:

![image](https://github.com/RND-Tech-and-Design/erindtherapy/assets/112582143/7da228b0-ac78-42e3-9b6d-89d088e9b4b0)

2024-01-09 01:01 UTC, RyanDrx commented on pages/about.vue
> +        text: "I am eager to help driven, smart, talented individuals embrace their strengths and start a career and life they aspire to.",
Ah ok, that's makes sense. .

2024-01-09 01:02 UTC, RyanDrx commented on components/AboutMePage/Intro.vue
> +const props = defineProps({ data: Object });
Thanks looks great

2024-01-09 20:35 UTC, PhoenixMP commented on package.json
> +        "@fortawesome/fontawesome-free": "^6.5.1",
Whoops, I thought I responded to this yesterday too. 

I used the <Icon> component and found similar icons:
![image](https://github.com/RND-Tech-and-Design/erindtherapy/assets/112582143/b73a01c9-2424-48cd-a251-75f55a203e67)

2024-01-09 23:54 UTC, RyanDrx approved these changes

2024-01-09 23:55 UTC, merged